import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { apiFetch } from '../../lib/supabase';

const STATUS_OPTIONS = ['pending', 'approved', 'rejected', 'paid'];

export default function Refunds() {
  const [refunds, setRefunds] = useState([]);
  const [loading, setLoading] = useState(true);

  const load = () => {
    setLoading(true);
    apiFetch('/admin/refunds').then((d) => setRefunds(d.data || [])).catch((e) => toast.error(e.message)).finally(() => setLoading(false));
  };
  useEffect(() => { load(); }, []);

  const updateStatus = async (r, status) => {
    try {
      await apiFetch(`/admin/refunds/${r.id}`, { method: 'PUT', body: JSON.stringify({ status }) });
      toast.success('Refund updated');
      load();
    } catch (err) { toast.error(err.message); }
  };

  return (
    <div>
      <h1 className="font-display text-2xl font-bold text-cream">Refunds queue</h1>
      <p className="mt-1 text-sm text-slate">Process refunds generated by cancellations, based on your cancellation policy.</p>
      <div className="card mt-6 overflow-x-auto !p-0">
        <table className="w-full min-w-[650px] text-left text-sm">
          <thead>
            <tr className="border-b border-white/10 text-xs uppercase tracking-wide text-slate">
              <th className="px-4 py-3 font-medium">Booking</th>
              <th className="px-4 py-3 font-medium">Customer</th>
              <th className="px-4 py-3 font-medium">Amount</th>
              <th className="px-4 py-3 font-medium">Status</th>
            </tr>
          </thead>
          <tbody>
            {loading && <tr><td colSpan={4} className="px-4 py-6 text-center text-slate">Loading…</td></tr>}
            {refunds.map((r) => (
              <tr key={r.id} className="border-b border-white/5 last:border-0 hover:bg-white/[0.02]">
                <td className="px-4 py-3 font-mono text-cream">{r.booking?.booking_reference}</td>
                <td className="px-4 py-3 text-cream">{r.booking?.customer?.full_name}</td>
                <td className="px-4 py-3 font-mono text-amber">KES {Number(r.amount).toLocaleString()}</td>
                <td className="px-4 py-3">
                  <select className="input !py-1.5" value={r.status} onChange={(e) => updateStatus(r, e.target.value)}>
                    {STATUS_OPTIONS.map((s) => <option key={s} value={s}>{s}</option>)}
                  </select>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
